### ISSUE TITLE
[ADD] labphew

### ISSUE THREAD

**Issue by SanliFaez** [UtrechtUniversity/awesome-utrecht-university#1]
**What is your project about?**
labphew (lowercase) is a minimalist functioning code module and folder structure for computer-controlled hardware. While trying to be a standalone and accessible module, labphew is, first and foremost, built to teach and exercise with computer-controlled measurements using Python.
https://labphew.readthedocs.io/en/latest/

**Why do you think your project is a great addition?**
labphew is meant to be:

+ out-of-the-box package, capable of communicating with Supported devices.
+ instructive code documentation that allows users to learn how it works and how to customize it.
+ a low entry-level template for building new user-interfaces for a measurement.
+ a good example of structuring lab-automation code and how to document it.
+ fun to play with, edit, and contribute to the code.

**Does your project fit into a category or do you want to suggest a new one?**
labphew matches a bit to all the categories. The closes category is research code.

**Comment by J535D165** [comment]
Dear @SanliFaez, thanks for your suggestion. Interesting and nice project. Are you interested in doing a PR? 

> Does your project fit into a category or do you want to suggest a new one?
labphew matches a bit to all the categories. The closes category is research code.

Yes I agree, maybe it fits best with Research Project Management?
https://github.com/UtrechtUniversity/awesome-utrecht-university#research-project-management. Maybe we should extend the description of Research Project Management with something like "lab tools".

**Comment by SanliFaez** [comment]
I think "lab tools" or "automation" could be a good (sub)category. 
what sort of PR do you have in mind @J535D165 ?

**Comment by kequach** [comment]
> I think "lab tools" or "automation" could be a good (sub)category. what sort of PR do you have in mind @J535D165 ?

You can create a Pull request to add your proposed changes to this repository. You can find more information here: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
Please note that you have to first fork the repository and add your changes to that. 
You can then create a new pull request here: https://github.com/UtrechtUniversity/awesome-utrecht-university/pulls
The reason for doing this instead of having us add your repository is that you will have contributed to the repository directly and you will be marked as a contributor:
![image](https://user-images.githubusercontent.com/18238845/135822687-26b70635-189f-4097-ad4a-41310cd76715.png)

If you need further assistance with this, I would be happy to help.

**Comment by kequach** [comment]
I added labphew to the category Research project management.
